### ISSUE TITLE
Licence/live server

### ISSUE THREAD

**Issue by mcintyre321** [agabani/HypermediaRedditDemo#1]
Hi, I'm a fellow Siren enthusiast, great project you have here!

I'm working on a site where you can register Siren clients and APIs and mash them together (http://apinest.com) with long term goals being increasing the profile of hypermedia. 

I'm collecting examples of Siren APIs and I'd be interested in getting your API and client [registered on there](http://apinest.com/ApiRegistrations). Email me if you're interested, its my username at gmail.com, thanks!

**Comment by agabani** [comment]
I've been meaning to separate the client and api onto 2 different servers, will register when api and client are on proper urls.

**Comment by agabani** [comment]
I've registered this project onto http://apinest.com under the alias:
- Hypermedia Reddit Demo Client [https://client-web-hypermediaredditdemo.azurewebsites.net]
- Hypermedia Reddit Demo API [https://api-web-hypermediaredditdemo.azurewebsites.net]

I would appreciate if the following is to remain on http://apinest.com, that credit be given to me:
- SirenReddit [http://sirenreddit.azurewebsites.net] [http://sirenreddit.azurewebsites.net/api]

**Comment by mcintyre321** [comment]
Hi thanks for doing that! I think I should have explained a bit more about what I'm hoping to do with apinest, as there are a couple of tweaks to your sites which would be very cool to do.

In the long term:
1. Provide a showcase of functional hypermedia APIs, on the http://apinest.com/ApiRegistrations url. I Right now, it just has 'Owner' which is the person who registered it, but I plan to add add a projectUrl, and creator links and stuff. 
2. Provide a showcase of proxies which can be run against any of the registered APIs, i.e. generic clients, or proxies that extend the functionality. (e.g. linting, analytics, security, generic (customisable) client generation)
3. Provide a place to 'mash up' the apis and proxies to enhance the APIs and re-use behaviour.

In the short term, I just want to have lots of Siren APIs to test my proxies and clients against, and enable other people to do the same.

Given that, I'm not sure your client is fits the plan for the proxy registrations, as I think it's hard-coded to point to your API? 

Apinest passes along a header `X-Destination: http://firstproxyinmashup http://secondproxyinmashup http://targetapihostname` which I use to direct the proxy to the target of the mashup (see [https://github.com/mcintyre321/SirenToHtmlClientProxy/.../ForwardProxyMessageHandler.cs](https://github.com/mcintyre321/SirenToHtmlClientProxy/blob/master/SirenToHtmlClientProxy/ForwardProxyMessageHandler.cs)).

If you're interested in writing a generic client, which will work against any of the Siren APIs on apinest.com you might like to extend your client to use that header?

Apologies if none of this aligns with anything you are interested in!
